2025-02-22 23:03:31,149 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-22 23:03:34,647 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-22 23:03:37,097 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-22 23:03:39,572 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-22 23:03:43,120 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-22 23:05:25,383 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-22 23:05:29,371 WARNING: Supabase logout failed for user Vincent.dangelo@gilmour.org: 'SUPABASE_ANON_KEY' [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:132]
2025-02-22 23:05:29,371 INFO: User Vincent.dangelo@gilmour.org logged out successfully [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:135]
2025-02-24 14:28:35,588 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-24 14:28:35,988 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-25 15:31:05,785 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-25 15:31:06,286 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 12:19:00,780 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 12:19:01,135 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 12:19:19,706 WARNING: Supabase logout failed for user babywho308@gmail.com: 'SUPABASE_ANON_KEY' [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:132]
2025-02-26 12:19:19,708 INFO: User babywho308@gmail.com logged out successfully [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:135]
2025-02-26 12:19:30,930 ERROR: Login error for user Vincent.dangelo@gilmour.org: Invalid login credentials [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:50]
2025-02-26 12:19:37,744 INFO: User Vincent.dangelo@gilmour.org logged in successfully [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:41]
2025-02-26 12:22:54,746 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 12:28:22,770 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 12:28:23,124 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 16:52:46,156 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 16:52:46,537 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 16:52:53,207 WARNING: Supabase logout failed for user Vincent.dangelo@gilmour.org: 'SUPABASE_ANON_KEY' [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:132]
2025-02-26 16:52:53,207 INFO: User Vincent.dangelo@gilmour.org logged out successfully [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:135]
2025-02-26 16:54:02,533 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 16:54:08,164 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 16:54:57,835 INFO: Attempting to register user: d03angelv@gmail.com [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:65]
2025-02-26 16:54:59,710 INFO: Supabase registration response: user=User(id='56375329-b41a-4789-8005-b5638eda446b', app_metadata={'provider': 'email', 'providers': ['email']}, user_metadata={'email': 'd03angelv@gmail.com', 'email_verified': False, 'phone_verified': False, 'sub': '56375329-b41a-4789-8005-b5638eda446b'}, aud='authenticated', confirmation_sent_at=datetime.datetime(2025, 2, 26, 21, 54, 58, 406898, tzinfo=TzInfo(UTC)), recovery_sent_at=None, email_change_sent_at=None, new_email=None, new_phone=None, invited_at=None, action_link=None, email='d03angelv@gmail.com', phone='', created_at=datetime.datetime(2025, 2, 26, 21, 54, 58, 371229, tzinfo=TzInfo(UTC)), confirmed_at=None, email_confirmed_at=None, phone_confirmed_at=None, last_sign_in_at=None, role='authenticated', updated_at=datetime.datetime(2025, 2, 26, 21, 54, 59, 679064, tzinfo=TzInfo(UTC)), identities=[UserIdentity(id='56375329-b41a-4789-8005-b5638eda446b', identity_id='d5755d2a-32ea-4428-94d2-ec65fe078533', user_id='56375329-b41a-4789-8005-b5638eda446b', identity_data={'email': 'd03angelv@gmail.com', 'email_verified': False, 'phone_verified': False, 'sub': '56375329-b41a-4789-8005-b5638eda446b'}, provider='email', created_at=datetime.datetime(2025, 2, 26, 21, 54, 58, 391646, tzinfo=TzInfo(UTC)), last_sign_in_at=datetime.datetime(2025, 2, 26, 21, 54, 58, 391580, tzinfo=TzInfo(UTC)), updated_at=datetime.datetime(2025, 2, 26, 21, 54, 58, 391646, tzinfo=TzInfo(UTC)))], is_anonymous=False, factors=None) session=None [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:73]
2025-02-26 16:55:01,592 INFO: Successfully created local user record for d03angelv@gmail.com [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:84]
2025-02-26 16:55:16,407 ERROR: Login error for user d03angelv@gmail.com: Email not confirmed [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:50]
2025-02-26 16:55:27,435 INFO: Attempting to register user: d03angelv@gmail.com [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:65]
2025-02-26 16:55:27,659 ERROR: Registration error for d03angelv@gmail.com: For security purposes, you can only request this after 30 seconds. [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:91]
2025-02-26 16:57:40,168 INFO: Attempting to register user: d03angelv@gmail.com [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:65]
2025-02-26 16:57:42,268 INFO: Supabase registration response: user=User(id='82d8f66b-bc6a-42ac-bbdc-0b05d872a654', app_metadata={'provider': 'email', 'providers': ['email']}, user_metadata={'email': 'd03angelv@gmail.com', 'email_verified': False, 'phone_verified': False, 'sub': '82d8f66b-bc6a-42ac-bbdc-0b05d872a654'}, aud='authenticated', confirmation_sent_at=datetime.datetime(2025, 2, 26, 21, 57, 40, 944114, tzinfo=TzInfo(UTC)), recovery_sent_at=None, email_change_sent_at=None, new_email=None, new_phone=None, invited_at=None, action_link=None, email='d03angelv@gmail.com', phone='', created_at=datetime.datetime(2025, 2, 26, 21, 57, 40, 930320, tzinfo=TzInfo(UTC)), confirmed_at=None, email_confirmed_at=None, phone_confirmed_at=None, last_sign_in_at=None, role='authenticated', updated_at=datetime.datetime(2025, 2, 26, 21, 57, 42, 233336, tzinfo=TzInfo(UTC)), identities=[UserIdentity(id='82d8f66b-bc6a-42ac-bbdc-0b05d872a654', identity_id='4a5fc793-8508-4d2a-8063-f0fbf67152b8', user_id='82d8f66b-bc6a-42ac-bbdc-0b05d872a654', identity_data={'email': 'd03angelv@gmail.com', 'email_verified': False, 'phone_verified': False, 'sub': '82d8f66b-bc6a-42ac-bbdc-0b05d872a654'}, provider='email', created_at=datetime.datetime(2025, 2, 26, 21, 57, 40, 934629, tzinfo=TzInfo(UTC)), last_sign_in_at=datetime.datetime(2025, 2, 26, 21, 57, 40, 934585, tzinfo=TzInfo(UTC)), updated_at=datetime.datetime(2025, 2, 26, 21, 57, 40, 934629, tzinfo=TzInfo(UTC)))], is_anonymous=False, factors=None) session=None [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:73]
2025-02-26 16:57:42,573 ERROR: Registration error for d03angelv@gmail.com: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "users_email_key"
DETAIL:  Key (email)=(d03angelv@gmail.com) already exists.

[SQL: INSERT INTO users (id, email, password_hash, created_at) VALUES (%(id)s::UUID, %(email)s, %(password_hash)s, %(created_at)s)]
[parameters: {'id': '82d8f66b-bc6a-42ac-bbdc-0b05d872a654', 'email': 'd03angelv@gmail.com', 'password_hash': None, 'created_at': datetime.datetime(2025, 2, 26, 21, 57, 42, 281460)}]
(Background on this error at: https://sqlalche.me/e/20/gkpj) [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:91]
2025-02-26 16:58:04,404 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 16:58:04,767 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 16:58:07,269 INFO: Attempting to register user: d03angelv@gmail.com [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:65]
2025-02-26 16:58:07,629 ERROR: Registration error for d03angelv@gmail.com: For security purposes, you can only request this after 33 seconds. [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:91]
2025-02-26 16:58:15,870 INFO: Attempting to register user: d03angelv@gmail.com [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:65]
2025-02-26 16:58:16,082 ERROR: Registration error for d03angelv@gmail.com: For security purposes, you can only request this after 24 seconds. [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:91]
2025-02-26 16:59:22,471 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 16:59:31,903 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 16:59:32,261 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 16:59:40,748 INFO: Attempting to register user: d03angelv@gmail.com [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:65]
2025-02-26 16:59:40,748 ERROR: Registration error for d03angelv@gmail.com: 'SyncSupabaseAuthClient' object has no attribute 'sign_up_with_password' [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:99]
2025-02-26 17:00:29,390 INFO: Access Point startup [in /Users/d_angel/Access_Point_V3/app/__init__.py:25]
2025-02-26 17:00:47,887 INFO: Attempting to register user: d03angelv@gmail.com [in /Users/d_angel/Access_Point_V3/app/routes/auth.py:65]
